# The 314 core cases at least one LPAR-paper abstraction variant lost on at least
# one model (flatevents, typeenrich, flat+guarddrop, flat+bridges:
# testresults/lpar_2026/core_t4-variant-*_2026-06-20 against testresults/milestones/core_two-stage_2026-06-03).
# Ids, inputs and expected values are tests/tests_core.py's.  Built 2026-08-26 for the
# max-abstract regression study.

[
# == PROPERTIES & ADJECTIVAL LOGIC ==
  [54, 'Frogs are small. John is a frog. John is a small animal?', None],
# == COREFERENCE & ANAPHORA ==
  [148, 'Mike ate berries in the forest bought by Mary. Mike ate berries in the forest bought by John?', None],
  [150, 'Bears ate berries in the forest bought by Mary. Bears ate berries in the forest bought by John?', None],
# == DEFINITE DESCRIPTIONS: X OF Y AND POSSESSIVES ==
  [218, 'John ate berries with the edge of a spoon. John ate berries with the edge of a fork?', None],
  [219, 'John ate berries with the edge of a spoon. John ate berries with the tip of a spoon?', None],
  [220, 'John ate berries with an edge of a spoon. John ate berries with an edge?', True],
# == POSSESSION INFERENCE FROM DESCRIPTIONS ==
  [289, 'John saw the head of Mary. John saw a head of Mary?', True],
  [291, 'John saw the head of Mary. John saw a head?', True],
  [309, "John saw Mary's head. John saw a head?", True],
  [319, "John saw elephant's head. John saw a head?", True],
  [322, 'John saw a head of an elephant. John saw a head of the elephant?', True],
  [324, 'John saw a head of the elephant. John saw a head of an elephant?', True],
  [325, 'John saw a head of an elephant. John saw a head of the bear?', None],
  [339, 'John saw a blue head of a red elephant. John saw a blue head of a red elephant?', True],
  [344, 'John saw a blue head of a red elephant. John saw a head of an elephant?', True],
  [346, 'The hand of a man moved a wheel. The hand of a man moved a wheel?', True],
  [350, 'A blue hand of a man moved a wheel of a large wheelbarrow. A blue hand of a man moved a wheel of a large wheelbarrow?', True],
  [351, 'A blue hand of a man moved a wheel of a large wheelbarrow. A blue hand of an elephant moved a wheel of a large wheelbarrow?', None],
  [352, 'The blue hand of a man moved a wheel of the large wheelbarrow. A blue hand of a man moved a wheel of a large wheelbarrow?', True],
  [353, 'The blue hand of a man moved the wheel of the large wheelbarrow. The blue hand of a man moved the wheel of the large wheelbarrow?', True],
  [355, 'A blue hand of a man moved a wheel of a large wheelbarrow. A hand moved a wheel?', True],
  [356, 'A blue hand of a man moved a wheel of a large wheelbarrow. A hand moved a wheelbarrow?', None],
  [357, 'A blue hand of a man moved a wheel of a large wheelbarrow. A blue hand moved a wheel?', True],
  [375, 'John does not eat a carrot. Mike eats carrots. Who eats carrots?', 'Mike'],
# == MEASURES ==
  [424, "The red car's length is 80 kilometers. What is the length of the red car?", ['80 kilometers', '80000 meters']],
# == QUANTIFIERS: UNIVERSAL & EXISTENTIAL ==
  [525, 'Bears eat all boxers. Mike is a boxer. Greg is a bear. Greg eats Mike?', True],
  [526, 'Bears eat most boxers. Mike is a boxer. Greg is a bear. Bears eats Mike?', 'Probably true.'],
  [527, 'Bears eat most boxers. Mike is a boxer. Greg is a bear. Bears eats Greg?', None],
  [528, 'Bears eat all boxers. Mike is a boxer. Bears eat boxers?', True],
  [529, 'Bears eat some boxers. Mike is a boxer. Bears eat Mike?', None],
# == COORDINATION (NP, VP, CLAUSAL) ==
  [565, 'Elephants and sparrows are either animals or birds. John is a sparrow. John is a bird. John is an animal?', False],
  [566, 'Elephants and sparrows are either animals or birds. John is a sparrow. Sparrows are birds. John is not an animal?', True],
# == LISTS AND CONJUNCTIONS ==
  [592, 'A red and blue flag waved. The flag was red?', True],
  [593, 'A red and blue flag waved. The flag was blue?', True],
  [594, 'John bought a red car and a blue bicycle. John bought a car?', True],
  [604, 'The students studied hard and passed the exam. Did the students pass the exam?', True],
  [605, 'The students studied hard and passed the exam. Did the students fail the exam?', False],
  [607, 'Mary washed and dried the cup. Mary dried the cup?', True],
  [618, 'Either John or Bill went to the store. Did someone go to the store?', True],
  [622, 'Red cars are not nice. Cars are nice. Red cars are nice?', False],
  [624, 'Penguins happily live in water. Penguins happily live in water?', True],
  [625, 'Penguins happily live in cold water. Penguins happily live in cold water?', True],
# == INTERNAL MODIFICATION ==
  [661, 'The car parked behind the house was blue. The car was behind the house?', True],
  [662, 'The car parked behind the house was blue. The car was in front of the house?', False],
  [663, 'The children playing in the garden laughed. The children were in the garden?', True],
  [665, 'The road leading to the village was narrow. The road led to the village?', True],
  [667, 'The tree growing near the river was tall. The tree grew near the river?', True],
  [673, 'The letter written by Mary was long. Mary wrote a long letter?', True],
  [675, 'The cake baked by John was sweet. John baked a sweet cake?', True],
  [676, 'The dog chased by the boy was black. The boy chased a black dog?', True],
  [701, 'Bears ate berries in a forest. Bears did not eat berries in a forest?', False],
  [702, 'Bears ate berries in a forest. Bears did not eat berries in a field?', None],
# == RELATIVE CLAUSES ==
  [716, 'Bears who are nice and who eat berries have a tail. John is a nice big bear. John eats berries. John has a tail?', True],
  [733, 'Nice bears who eat big fish are strong. John is a nice bear. John eats fish. John is strong?', None],
  [738, 'The bear who is big eats fish. The bear who is big eats fish?', True],
  [739, 'The bear who is white eats fish. The bear who is white eats fish?', True],
  [742, 'The bear who was white ate a fish. The white bear ate a fish?', True],
  [743, 'Bears who were nice ate. Nice bears ate?', True],
  [745, 'Bears who are nice eat fish who are strong. John is a nice bear. Bears who are nice eat fish?', True],
  [746, 'Bears who are nice eat fish who are strong. John is a nice bear. Bears who are nice eat tables?', None],
  [747, 'Bears who are nice eat fish who are strong. John is a nice bear. Bears who are nice eat fish who are strong?', [True, 'Likely true']],
  [748, 'Bears who are nice eat fish who are strong. John is a nice bear. Nice bears eat strong fish?', [True, 'Likely true']],
  [753, 'The bear who was white and ate a fish was cool. The white bear who ate a fish was cool?', True],
  [754, 'The bear who was white and ate a fish was cool. The bear who ate a fish was cool?', True],
  [759, 'The bear who was white and ate a big fish was cool. The white bear who ate a strong fish was cool? ', None],
  [763, 'The nice bear who was white and ate a big fish also ate blue berries. The white nice bear who ate a big fish also ate berries? ', True],
  [767, 'The bear who ate a big fish ate blue berries. The bear who ate a fish ate big berries?', None],
  [776, 'Bears eat fish who are strong. John is a bear. John eats strong fish?', True],
  [777, 'Bears eat fish who are strong. John is a fox. John eats strong fish?', None],
  [778, 'Bears eat fish who are strong. John is a bear. John eats red fish?', None],
  [779, 'Bears eat red fish who are strong. John is a bear. John eats red strong fish?', True],
  [780, 'Bears eat red fish who are strong. John is a bear. John eats yellow strong fish?', None],
  [781, 'Bears eat red fish who are strong. John is a bear. John eats yellow fish?', None],
  [782, 'Bears who are nice eat fish who are strong. John is a nice bear. John eats strong fish?', True],
  [783, 'Bears who are nice eat fish who are strong. John is a bear. John eats strong fish?', None],
  [784, 'Bears who are nice eat fish who are strong. John is a nice bear. John eats yellow fish?', None],
  [785, 'Bears who are nice and white eat fish who are strong and red. John is a nice white bear. John eats red strong fish?', True],
  [786, 'Bears who are nice and white eat fish who are strong and red. John is a nice bear. John eats red strong fish?', None],
  [787, 'Bears who are nice and white eat fish who are strong and red. John is a nice white bear. John eats yellow strong fish?', None],
  [789, 'A man liked a car which a woman bought. The car was red. The man liked the red car which a woman bought?', True],
  [800, 'Bears ate berries in a forest which was bought by Mary. Bears ate berries in the forest bought by John?', None],
  [805, 'Bears ate berries in the forest which was bought by Mary. Bears ate berries in the forest which was bought by Mary?', True],
  [807, 'Bears ate berries in the forest which was bought by Mary. Bears ate berries in the forest bought by Mary?', True],
  [810, 'Bears ate nice berries in a big forest which was bought by Mary. Bears ate berries in the forest which was bought by her?', True],
  [818, 'John lives in a car which is red. John lives in a red car?', True],
  [819, 'John lives in a car which is red. John lives in a nice car?', None],
  [820, 'John lives in a car which is red and was bought by Mary. The nice car was bought by Mary?', None],
  [845, 'John drove a car which Eve bought. John drove a car which Eve bought?', True],
  [848, 'John drove a car which Eve bought. John drove a car Eve bought?', True],
  [851, 'John drove a car Mike bought. John drove a car Mike bought?', True],
  [854, 'John drove a car Mike bought. John drove a car which Mike bought?', True],
  [858, 'John drove a car Eve bought. John drove a car?', True],
  [859, 'John drove a red car Mike bought. John drove a car which Mike bought?', True],
  [860, 'John drove a red car which Eve bought. John drove a car Eve bought?', True],
  [890, 'The car which John drove was red. What color was the car?', 'Red.'],
  [893, 'The student who passed the test studied a lot. Did the student fail the test?', False],
  [902, 'A man had a car which a nice woman bought. The car was red. Who bought a car?', 'The nice woman'],
  [904, 'A man had a car which a nice woman bought. The car was red. Who was nice and bought a car?', ['The woman', 'The nice woman.']],
  [917, 'A man liked a car which a woman bought. The car was red. The man liked a black car?', None],
  [918, 'A man liked a car which a woman bought. The car was red. The man liked the red car?', True],
  [930, 'A man drove a car which a woman bought. A man drove a car which a woman bought?', True],
  [931, 'A man drove a car a woman bought. A man drove a car which a woman bought?', True],
  [932, 'A man drove a car which a woman bought. A man drove a car a woman bought?', True],
  [934, 'A man drove a car which a woman bought. A man drove a car?', True],
  [935, 'A man drove a car which a woman bought. A man drove the car?', True],
  [956, 'Bears who eat fish which are big are strong. John is a bear. John eats fish. John is strong?', None],
  [958, 'A man who ate breakfast liked a car which a woman bought. The car was red.\n     A man who ate breakfast liked a red car which a woman bought?', True],
  [962, 'A man liked a car which a woman bought. The car was red. Who liked a red car?', 'The man'],
  [964, 'A man liked a car which a nice woman bought. The car was red. Who bought a car?', 'The nice woman'],
  [966, 'A man liked a car which a nice woman bought. The car was red. Who was nice and bought a car?', 'The woman'],
# == AMBIGUOUS MODIFIER SCOPE ==
  [972, 'John ate the apple quickly. How did John eat the apple?', 'Quickly.'],
  [974, 'Mary visited London in September. When did Mary visit London?', 'In September.'],
  [979, 'John works at the hospital every day. Where does John work?', 'At the hospital.'],
  [980, 'John works at the hospital every day. Does John work at the school?', None],
  [981, 'John ate berries with the help of a spoon. John ate berries with the help of a spoon?', True],
  [982, 'John ate berries with the help of a spoon. John ate berries with the help of a spade?', None],
  [985, 'John saw the bird in the garden. The bird was in the garden?', True],
  [987, 'John ate the pizza on the table. Where was the pizza?', 'On the table.'],
  [988, 'John ate the pizza on the table. Was the pizza on the floor?', False],
  [994, 'Mary found the key under the table. The key was under the table?', True],
  [995, 'Mary found the key under the table. Was the key on the table?', False],
  [996, 'Tom put the book on the chair. The book was on the chair?', True],
  [997, 'Eve kept the milk in the fridge. The milk was in the fridge?', True],
  [1001, 'Mary called the boy in the kitchen. The boy was in the kitchen?', True],
  [1002, 'John shot an elephant in his pyjamas. John shot in his pyjamas?', True],
  [1003, 'John ate berries in a forest with a spoon. John ate berries in a forest with a spoon?', True],
  [1004, 'John ate berries in a forest with a spoon. John ate berries in a field?', None],
  [1005, 'John ate berries in a forest with a spoon. John ate berries in a nice forest with a spoon?', None],
# == PASSIVE VOICE ==
  [1017, 'John was defeated. John was defeated?', True],
  [1018, 'Clinton defeated Dole. Clinton defeated Dole?', True],
  [1020, 'Dole was defeated by Clinton. Dole was defeated by Clinton?', True],
  [1022, 'Clinton defeated Dole. Dole was defeated by Clinton?', True],
  [1024, 'Dole was defeated by Clinton. Clinton defeated Dole?', True],
  [1049, 'Mary was given a promotion. Who received a promotion?', 'Mary.'],
# == SUBORDINATE CLAUSES ==
  [1056, 'John said that Mary left. Mary left?', True],
  [1058, 'Eve reported that Tom arrived. Tom arrived?', True],
  [1060, 'Anna announced that the show started. The show started?', True],
  [1061, 'The guide explained that the road was closed. Was the road open?', False],
  [1062, 'John went to the shop to buy bread. John went to the shop?', True],
  [1083, 'Mary said that she was tired. Who was tired?', 'Mary.'],
  [1086, 'The horse kept in the stable was calm. The horse was in the stable?', True],
# == ELLIPSIS & GAPPING ==
  [1089, 'John went to Paris and Mary to London. Where did Mary go?', ['London.', 'To London.']],
  [1094, 'John bought a book, and Bill said Peter did too. Did Bill say Peter bought a book?', True],
  [1095, 'If John wrote a report, then Bill did too. John wrote a report. Did Bill write a report?', True],
# == ACTION MODES & HABITS ==
  [1097, 'Bears eat berries in a forest. Bears eat berries in a forest?', True],
  [1098, 'Bears eat berries in a forest. Bears eat berries in a big forest?', None],
  [1100, 'Bears quickly eat berries in a forest. Bears eat berries?', True],
  [1101, 'Bears quickly eat berries in a forest. Bears quickly eat berries?', True],
  [1102, 'Bears quickly eat berries in a forest. Bears slowly eat berries?', None],
  [1103, 'Bears eat red berries in a forest. Bears eat berries in forest?', True],
  [1105, 'Bears eat berries in a deep forest. Bears eat berries?', True],
  [1106, 'Bears eat berries in a deep forest. Bears eat berries in a deep forest?', True],
  [1107, 'Bears eat berries in a deep forest. Bears eat berries in a forest?', True],
  [1108, 'Bears eat berries in a deep forest. Bears eat berries in a shallow forest?', None],
  [1109, 'Bears eat red berries in a deep forest. John is a bear. John eats red berries in a deep forest?', True],
  [1110, 'Bears eat red berries in a deep forest. John is a bear. John eats no berries?', False],
  [1111, 'Bears eat berries in a deep forest. John is a bear. John eats berries in a shallow forest?', None],
  [1112, 'Bears quickly eat berries in a deep forest. John is a bear. John quickly eats berries in a deep forest?', True],
  [1113, 'If a bear quickly eats berries in a deep forest, it is hungry. John is a bear.\n     John quickly eats berries in a deep forest. John is hungry?', True],
  [1114, 'If a bear quickly eats berries in a deep forest, it is hungry. John is a bear.\n     John eats berries in a deep forest. John is hungry?', None],
  [1115, 'If a bear quickly eats berries in a deep forest, it is hungry. John is a fox.\n     John quickly eats berries in a deep forest. John is hungry?', None],
  [1116, 'If a bear eats berries in a forest, it is hungry. John is a brown bear.\n      John quickly eats berries in a deep forest. Who is hungry?', 'John.'],
  [1118, 'If a bear eats, it is hungry. John is a brown bear.\n      John quickly eats berries in a deep forest. Who is hungry?', 'John.'],
  [1119, 'Penguins live in the water. Penguins live in the water?', True],
  [1120, 'Penguins live in the water. Penguins live in water?', True],
  [1121, 'Penguins live in the water. Penguins live in stone?', None],
  [1122, 'Penguins live in the water. Penguins live in the stone?', None],
  [1123, 'Penguins live in water. Penguins live in water?', True],
  [1124, 'Penguins live in water. Penguins live in stone?', None],
  [1125, 'Penguins live in water. Penguins live in the stone?', None],
  [1126, 'Penguins happily live in cold water. Penguins live in water?', True],
  [1127, 'Penguins happily live in cold water. Penguins live in cold water?', True],
  [1128, 'Bears eat berries in a forest. Bears eat berries in forest?', True],
  [1129, 'Bears eat berries in a forest. Bears do not eat berries in forest?', False],
  [1130, 'Bears eat berries in a forest. Bears eat berries in a field?', None],
  [1131, 'Bears eat berries in a forest. Bears eat berries?', True],
# == TRANSFER OF POSSESSION (GIVE/TAKE) ==
  [1132, 'John gave Mary a book. Who received a book?', 'Mary.'],
  [1134, 'John gave a book to Mary. What did Mary receive?', ['A book.', 'The book.']],
  [1136, 'Anna handed Mark a key. Mark got a key?', True],
  [1139, 'The teacher showed the students the map. Who saw the map?', ['The students.', 'The teacher and the students.']],
  [1141, 'The teacher showed the map to the students. What did the teacher show?', 'The map.'],
  [1142, 'John told Mary a story. Mary heard a story?', True],
  [1144, 'John told a story to Mary. Who heard a story?', 'Mary.'],
  [1146, 'The chef cooked a meal for the guests. Who was the meal for?', 'The guests.'],
  [1148, 'Susan bought herself a new car. Who owns a new car?', 'Susan.'],
  [1150, 'Susan bought a new car for herself. What did Susan buy?', ['A new car.', 'A car.']],
  [1151, 'John gave Mary a book. Mary got a book?', True],
  [1153, 'John gave a book to Mary. Mary got a book?', True],
  [1155, 'Eve sent a letter to Tom. Who got a letter?', 'Tom.'],
  [1156, 'The teacher showed the students a map. The students saw a map?', True],
  [1158, 'The teacher showed a map to the students. Who saw a map?', ['The students.', 'The teacher and the students.']],
  [1159, 'John gave Mary a red book. Mary got a red book?', True],
  [1162, 'Anna handed Mark a silver key. Mark got a silver key?', True],
  [1163, 'The teacher showed the students a large map. The students saw a large map?', True],
  [1165, 'Bears eat red berries in a forest. Bears eat red berries in forest?', True],
  [1166, 'Bears eat red berries in a forest. Bears eat yellow berries in forest?', None],
# == TENSE, ASPECT & CHANGE OF STATE ==
  [1172, 'John has finished his homework. Is the homework finished?', True],
  [1173, 'John has finished his homework. Is the homework unfinished?', False],
  [1176, 'The train leaves at noon. When does the train leave?', 'At noon.'],
  [1188, 'While John was cooking, Mary read a book. Mary read a book?', True],
  [1196, 'Since Mike lost his ticket, he stayed outside. Mike stayed outside?', True],
  [1198, 'Until Sara arrived, John waited. Sara arrived?', True],
  [1203, 'Before Mary wrote a letter, she found a pen. Mary found a pen?', True],
  [1205, 'John stopped smoking. Did John smoke in the past?', True],
  [1206, 'John stopped smoking. Does John smoke now?', False],
  [1207, 'Mary started the car. Was the car running before?', False],
# == SPATIAL LOGIC & WHERE QUERIES ==
  [1274, 'Birds near Tallinn are nice. John is near Tallinn. What is nice?', 'A bird near Tallinn'],
  [1277, 'John ate candy in a house. John ate meat in a room. Where did John eat candy?', 'In a house'],
  [1278, 'John ate candy in a house. John ate meat in a room. Where did John eat meat?', 'In a room'],
  [1279, 'John ate candy in a house. John ate meat at a room. Where did John eat?', ['At a room and in a house', 'In a house and at a room.', 'In a house.', 'At a room.']],
  [1281, 'John jumped high in a room. John jumped low near the garage. Where did John jump high?', 'In a room'],
  [1282, 'John jumped high in a room. John jumped low near the garage. Where did John jump low?', 'Near the garage'],
  [1283, 'John jumped high in a room. John jumped low near the garage. Where did John jump quickly?', None],
  [1284, 'Bears ate berries in a forest which was bought by Mary. Mary bought the forest where the bears ate?', True],
  [1285, 'Bears ate berries in a forest which was seen by Mary. Mary saw the forest where the bears ate?', True],
  [1288, 'Bears ate berries in a forest which was bought by Mary. Mary bought the forest where the bears ate honey?', None],
  [1289, 'John lives in a red car bought by Mary. Mary bought the car where John ate?', None],
  [1290, 'John lives in a red car bought by Mary. Mary bought the car where Mike lives?', None],
  [1291, 'During 1800, John jumped in a house. During 1800, John jumped?', True],
  [1293, 'During 1800, John jumped in a house. When did John jump?', ['During the year 1800', 'During 1800.']],
  [1295, 'Before 1900, John jumped in a house. When did John jump?', ['Before the year 1900', 'Before 1900.']],
  [1296, 'Before 1900, John jumped in a house. After 1902, John ate in a house. When did John jump?', ['Before the year 1900', 'Before 1900.']],
  [1297, 'Before 1900, John jumped in a house. After 1902, John sat in a house. When did John sat?', ['After the year 1902', 'After 1902.']],
  [1299, 'On Monday, John jumped in a house. When did John jump?', 'On Monday'],
# == ACTION AND WORLD STATE SEQUENCES ==
  [1304, 'John travelled to the hallway. Mary journeyed to the bathroom. Where is John?', ['hallway', 'In the hallway.', 'At the hallway.']],
  [1305, 'John travelled to the hallway. Mary journeyed to the bathroom. Daniel went back to the bathroom. John moved to the bedroom. Where is Mary?', ['bathroom', 'In the bathroom.', 'At the bathroom.']],
  [1306, 'John travelled to the hallway. Mary journeyed to the bathroom. Daniel went back to the bathroom. John moved to the bedroom. John went to the hallway. Sandra journeyed to the kitchen. Where is Sandra?', ['kitchen', 'In the kitchen.', 'At the kitchen.']],
  [1307, 'John travelled to the hallway. Mary journeyed to the bathroom. Daniel went back to the bathroom. John moved to the bedroom. John went to the hallway. Sandra journeyed to the kitchen. Sandra travelled to the hallway. John went to the garden. Where is Sandra?', ['hallway', 'In the hallway.', 'At the hallway.']],
  [1308, 'John travelled to the hallway. Mary journeyed to the bathroom. Daniel went back to the bathroom. John moved to the bedroom. John went to the hallway. Sandra journeyed to the kitchen. Sandra travelled to the hallway. John went to the garden. Sandra went back to the bathroom. Sandra moved to the kitchen. Where is Sandra?', ['kitchen', 'In the kitchen.', 'At the kitchen.']],
  [1309, 'Sandra travelled to the kitchen. Sandra travelled to the hallway. Where is Sandra?', ['hallway', 'In the hallway.', 'At the hallway.']],
  [1310, 'Sandra travelled to the kitchen. Sandra travelled to the hallway. Mary went to the bathroom. Sandra moved to the garden. Where is Sandra?', ['garden', 'In the garden.', 'At the garden.']],
  [1311, 'Sandra travelled to the kitchen. Sandra travelled to the hallway. Mary went to the bathroom. Sandra moved to the garden. Sandra travelled to the office. Daniel journeyed to the hallway. Where is Daniel?', ['hallway', 'In the hallway.', 'At the hallway.']],
  [1312, 'Sandra travelled to the kitchen. Sandra travelled to the hallway. Mary went to the bathroom. Sandra moved to the garden. Sandra travelled to the office. Daniel journeyed to the hallway. Daniel journeyed to the office. John moved to the hallway. Where is Sandra?', ['office', 'In the office.', 'At the office.']],
  [1313, 'Sandra travelled to the kitchen. Sandra travelled to the hallway. Mary went to the bathroom. Sandra moved to the garden. Sandra travelled to the office. Daniel journeyed to the hallway. Daniel journeyed to the office. John moved to the hallway. John travelled to the bathroom. John journeyed to the office. Where is Daniel?', ['office', 'In the office.', 'At the office.']],
# == QUESTION LOGIC (WHO/WHAT/WHICH) ==
  [1318, 'John Sweeney is a car. John Smith is bad. Who is John Sweeney?', 'A car.'],
  [1319, 'John Sweeney is a car. Who is John?', ['John Sweeney is a car.', 'A car.', 'John Sweeney.']],
  [1320, 'John Sweeney is cool and bought a car. John is a bad baby man. John is not big. Who is John?', ['John Sweeney is a not big cool bad baby man.', 'John Sweeney.', 'A cool baby man.', 'A cool baby and a man.']],
# == IF-THEN INFERENCE ==
  [1366, 'If X1 is a father of Y1, Y1 is a child of X1.\n      If X1 is a father of Y1 and Y1 is a father of Z1, X1 is a grandfather of Z1.\n      John is a father of Mike and Mickey. Luke is a father of John.\n      If X1 is a grandfather of Y1, Y1 is a grandchild of X1.\n      If X1 is male and X1 is a grandchild of Y1, X1 is a grandson of Y1.\n      Mike or Mickey are not female. Any person is male or female.\n      Who is a grandson of Luke?', 'Mike or Mickey.'],
  [1398, 'If a big bear who eats strong fish is white, it is nice. John is a big bear. John eats strong fish. John is white. John is nice?', True],
  [1400, 'If a big bear who eats strong fish is white, it is nice. John is a big bear. John eats strong fish. John is nice?', None],
  [1401, 'If a big bear who eats strong fish is white, it is nice. John is a big bear. John eats yellow fish. John is white. John is nice?', None],
# == DEFAULT & DEFEASIBLE REASONING ==
  [1407, 'Penguins are birds who do not fly. Birds fly. John is a penguin. John flies?', False],
  [1413, 'Red cars are not nice. Cars are nice. Red cars are not nice?', True],
  [1415, 'Red cars are not nice. Cars are nice. What are not nice?', 'A red car.'],
  [1417, 'Red cars do not have trunks. Cars have trunks. Red cars have trunks?', False],
  [1419, 'Red cars do not have trunks. Cars have trunks. Red cars have a trunk?', False],
  [1422, 'Red cars do not have trunks. Cars have trunks. John is a red car. John has a trunk?', False],
  [1426, 'Penguins are birds. Penguins do not fly. Birds fly. Who does not fly?', 'A penguin.'],
  [1429, 'Birds fly and eat. Baby birds do not fly. John is a baby bird. Mike is a bird.\n    John does not fly?', True],
  [1431, 'Birds fly and eat. Baby birds do not fly. John is a baby bird. Mike is a bird.\n    John runs?', None],
  [1432, 'Birds fly and eat. Baby birds do not fly. John is a baby bird. Mike and Eve are birds.\n    Who does not fly?', 'John.'],
  [1434, 'Birds fly and eat. Baby birds do not fly. John is a baby bird. Mike and Eve are birds.\n    Who eats?', ['John, Mike and Eve.', 'John, Mike, and Eve.', 'Mike and Eve.']],
  [1435, 'Birds fly and eat. Baby birds do not fly. John is a baby bird. Mike and Eve are birds.\n    Who flies and eats?', 'Mike and Eve.'],
  [1436, 'Birds fly and eat. Baby birds do not fly. John is a baby bird. Mike and Eve are birds.\n    Who flies or eats?', 'John, Mike and Eve.'],
  [1437, 'Birds fly and eat. Baby birds do not fly. John is perhaps a baby.\n     Mike and Eve and John are birds. Who flies and eats?', ['Mike, Eve and likely John', 'Mike and Eve.']],
  [1438, 'Bears eat berries. Baby bears do not eat berries. John is a bear.\n     John eats berries?', True],
  [1439, 'Bears eat berries. Baby bears do not eat berries. John is a baby bear.\n     John eats berries?', False],
  [1440, 'Bears eat berries. Baby bears eat no berries. John is a baby bear.\n     John eats berries?', False],
  [1441, 'Bears eat berries. Baby bears do not eat berries. John and Mike are bears.\n      John is a baby bear.\n      Who eats berries?', 'Mike.'],
  [1443, 'Birds can fly. Baby birds can not fly. John is a baby bird. Mike and Eve are birds.\n      Who can not fly?', 'John.'],
  [1445, 'Bears can eat berries. Baby bears can not eat berries. John and Mike are bears.\n      John is a baby bear.  Who can not eat berries?', 'John.'],
  [1446, 'Birds fly. No penguin can fly. Penguins are birds. John is a penguin. John can fly?', False],
  [1447, 'Birds fly. No penguin can fly. Penguins are birds. John is a penguin. John flies?', False],
  [1450, 'Birds fly. No penguin can fly. Penguins are birds. John is a bird. John flies?', True],
  [1453, 'Birds fly. Baby birds can not fly. John is a baby bird. Mike is a bird. Who does not fly?', 'John'],
  [1455, 'Birds fly. Baby birds can not fly. John is a baby bird. Mike is a bird. Who can not fly?', 'John'],
  [1456, 'Bears eat berries. Baby bears can not eat berries. John and Mike are bears.\n      John is a baby bear.  Who eats berries?', 'Mike.'],
  [1457, 'Bears eat berries. Baby bears can not eat berries. John and Mike are bears.\n      John is a baby bear.  Who does not eat berries?', 'John.'],
  [1458, 'Birds can fly. Baby birds do not fly. John is a baby bird. Mike is a bird. Who can not fly?', 'John.'],
  [1459, 'Bears can eat berries. Baby bears do not eat berries. John and Mike are bears.\n      John is a baby bear.  Who can not eat berries?', 'John.'],
  [1461, 'John is a car. John is bad. Who is John?', ['John is a bad car.', 'A car.']],
  [1462, 'John is a car. John is bad. Who is John?', ['John is a bad car.', 'A car.']],
  [1464, 'Elephants are big. Young elephants are not big.\n      Mike is an elephant. John is a young elephant. John is big?', False],
  [1466, 'Elephants are big. Young elephants are not big.\n      Mike is an elephant. John is a young elephant. Who is not big?', 'John.'],
  [1467, 'Elephants are big. Young elephants are not big.\n      Who is big?', ['An elephant.', 'Elephants that are not young.']],
  [1468, 'Elephants are big. Young elephants are not big.\n      Who is not big?', 'A young elephant.'],
# == DEFAULTS WITH EXCEPTIONS (BLOCKING) ==
  [1469, 'Bears eat berries. John is a bear. John eats berries?', True],
  [1470, 'Bears eat berries. John is a bear. John eats some berries?', True],
  [1471, 'Bears eat berries. John is a bear. John eats all berries?', None],
  [1472, 'Bears eat all berries. John is a bear. John eats all berries?', True],
  [1473, 'Some bears eat all berries. John is a bear. John eats berries?', None],
  [1474, 'Some bears eat all berries. Some bears eat berries?', True],
  [1475, 'If a bear eats red berries, it is big. John eats berries. John is a bear.\n     John is big?', None],
  [1476, 'If a bear eats red berries, it is big. John eats red berries. John is a bear.\n     John is big?', True],
  [1477, 'If X1 eats berries, it is a bear. John eats red berries. John is a bear?', True],
# == UNCERTAINTY & CONFIDENCE ==
  [1481, 'Elephants are rarely animals. John is an elephant. John is an animal?', 'Probably false.'],
  [1483, 'Probably elephants are not animals. John is an elephant. John is an animal?', 'Probably false.'],
  [1508, 'It is false that elephants are animals. John is an elephant. John is an animal?', False],
  [1509, 'It is not true that elephants are animals. John is an elephant. John is an animal?', False],
  [1512, 'It is probably false that elephants are animals. John is an elephant. John is an animal?', 'Probably false.'],
  [1514, 'It is not probable that elephants are animals. John is an elephant. John is an animal?', 'Probably false.'],
  [1515, 'It is unlikely that elephants are animals. John is an elephant. John is an animal?', 'Probably false.'],
  [1529, 'John smokes tobacco with a probability 0.8. What does John smoke?', ['Likely a tobacco', 'Tobacco.']],
  [1530, 'John smokes tobacco with a probability 0.8. John smokes?', 'Likely true'],
  [1531, 'John smokes tobacco with a probability 80 percent. Does John smoke?', 'Likely true'],
  [1533, 'Birds fly and eat. Baby birds do not fly. John is hardly a baby bird.\n     Mike and Eve and John are birds. Who flies and eats?', ['Mike, Eve and John', 'Mike, Eve, and John.']],
  [1534, 'Birds fly and eat. Baby birds do not fly. John is probably a baby bird.\n     Mike and Eve and John are birds. Who flies and eats?', 'Mike and Eve'],
  [1549, 'John probably smokes. John smokes?', 'Probably true'],
  [1550, 'Probably John smokes. John smokes?', 'Probably true'],
  [1551, 'It is probably true that John smokes. John smokes?', 'Probably true'],
  [1552, 'John smokes with a probability 90%. John smokes?', 'Likely true'],
  [1553, 'John smokes with a probability 90 percent. John smokes?', 'Likely true'],
  [1554, 'John smokes with a probability 0.9. John smokes?', 'Likely true'],
  [1556, 'John smokes tobacco with a probability 0.8. John smokes what?', ['Likely a tobacco', 'Tobacco.']],
# == ADVANCED SEMANTIC OPERATORS ==
  [1567, 'Eve failed to finish the report. Eve finished the report?', False],
  [1573, 'Tom refused to eat the soup. Tom ate the soup?', False],
  [1575, 'Eve forgot to lock the door. Eve locked the door?', False],
  [1577, 'John was seen to enter the room. John entered the room?', True],
  [1579, 'Mary was heard to sing. Mary sang?', True],
  [1581, 'Only John bought a car. Did Mary buy a car?', False],
  [1582, 'Only John bought a car. Who bought a car?', 'John.'],
  [1583, 'John only eats apples. Does John eat bananas?', False],
  [1584, 'Everyone except John arrived. Did John arrive?', False],
  [1588, 'Tom had the mechanic fix his car. Who fixed the car?', 'The mechanic.'],
]
