"""EB negative controls, built by tools/graph_eb_negatives.py.

Every EB case in the 165-cohort is accepted True, so EB measures
recall alone.  These 60 cases give the family its other two
answers: 40 Unknown controls (one case's passage, another case's
hypothesis) and 20 False controls (the case's own hypothesis,
negated).  Do not edit by hand; rebuild from the tool.
"""

tests = [
  ['ebn-0001',
   'Moisture is water in liquid form. Water is a kind of substance. Freezing means a substance changes from a liquid into a solid by decreasing heat energy. There is moisture on the surface of the airplane. An airplane is climbing in the sky. Climbing increases altitude. As altitude increases , the temperature of the air will decrease in the troposphere. Water is in the solid state , called ice. Is it true that heat, light, and sound are all different forms of energy?',
   ['unknown']],
  ['ebn-0002',
   'Moisture is water in liquid form. Water is a kind of substance. Freezing means a substance changes from a liquid into a solid by decreasing heat energy. There is moisture on the surface of the airplane. An airplane is climbing in the sky. Climbing increases altitude. As altitude increases , the temperature of the air will decrease in the troposphere. Water is in the solid state , called ice. Is it true that the water from the melted ice cube will then evaporate?',
   ['unknown']],
  ['ebn-0003',
   'Moisture is water in liquid form. Water is a kind of substance. Freezing means a substance changes from a liquid into a solid by decreasing heat energy. There is moisture on the surface of the airplane. An airplane is climbing in the sky. Climbing increases altitude. As altitude increases , the temperature of the air will decrease in the troposphere. Water is in the solid state , called ice. Is it true that fog can be formed by ocean water evaporating and then condensing in the air?',
   ['unknown']],
  ['ebn-0004',
   'A pebble is a kind of small rock. Rocks interacting with moving water over long periods of time causes weathering. Waves are made of moving water. Sometimes weathering smooths rocks. Is it true that lichens producing acid to break down rocks is an example of chemical weathering?',
   ['unknown']],
  ['ebn-0005',
   'A class of something means a type of something. Classifying is when one sorts something by kind / type. Class is a measure of how a rock is formed. Igneous rocks are formed by magma cooling / crystallizing. Is it true that rocks are classified as igneous, sedimentary, or metamorphic based on how they are formed?',
   ['unknown']],
  ['ebn-0006',
   'The skeletal system is used to give structure for the body of animals. Muscular movement helps animals move. The muscular system contains muscles. Microtubules in eukaryotic organisms help cells move. If two things perform the same function then those two things are similar. Microfilaments in eukaryotic organisms give cells structure. Is it true that releasing energy is used by muscles to move parts of the body?',
   ['unknown']],
  ['ebn-0007',
   'Height is an inherited characteristic. Inheriting is when an inherited characteristic is copied / is passed from parent to offspring by genetics / dna. Is it true that hunting is a learned characteristic and not an inherited characteristic?',
   ['unknown']],
  ['ebn-0008',
   "An adaptation has a positive impact on a living thing 's survival. Drier means lower in amount of water. Living things require water for survival. If something increases something else then that something has a positive impact on that something else. Storing water increases the water available to organisms in a dry environment. A dry environment is low in availability of water. Is it true that plants on tropical rainforest floors grow large leaves due to the low availability of sunlight?",
   ['unknown']],
  ['ebn-0009',
   "As the size of a leaf increases , the amount of sunlight absorbed by that leaf will increase. An adaptation / an ability has a positive impact on an animal 's / living thing 's survival / health / ability to reproduce. Large canopies / trees block sunlight from reaching the ground. Forest canopies blocking sunlight decreases the availability of sunlight on the forest floor. Larger means greater / higher / more / increase in size. A leaf is a part of a green plant. Tropical rainforests contain many large trees. A plant requires sunlight for photosynthesis. A leaf absorbs sunlight to perform photosynthesis. A plant is a kind of living thing. A required resource being low in availability has a negative impact on the something that requires that resource. A plant requires photosynthesis to grow / survive. If a living thing must do something to survive, then increasing that living thing's ability to do that something has a positive impact on that living thing's survival. Is it true that ability to store water is a kind of adaptation to a dry environment?",
   ['unknown']],
  ['ebn-0010',
   "As the size of a leaf increases , the amount of sunlight absorbed by that leaf will increase. An adaptation / an ability has a positive impact on an animal 's / living thing 's survival / health / ability to reproduce. Large canopies / trees block sunlight from reaching the ground. Forest canopies blocking sunlight decreases the availability of sunlight on the forest floor. Larger means greater / higher / more / increase in size. A leaf is a part of a green plant. Tropical rainforests contain many large trees. A plant requires sunlight for photosynthesis. A leaf absorbs sunlight to perform photosynthesis. A plant is a kind of living thing. A required resource being low in availability has a negative impact on the something that requires that resource. A plant requires photosynthesis to grow / survive. If a living thing must do something to survive, then increasing that living thing's ability to do that something has a positive impact on that living thing's survival. Is it true that soil is a kind of resource that provides minerals that plants need to grow?",
   ['unknown']],
  ['ebn-0011',
   "As the size of a leaf increases , the amount of sunlight absorbed by that leaf will increase. An adaptation / an ability has a positive impact on an animal 's / living thing 's survival / health / ability to reproduce. Large canopies / trees block sunlight from reaching the ground. Forest canopies blocking sunlight decreases the availability of sunlight on the forest floor. Larger means greater / higher / more / increase in size. A leaf is a part of a green plant. Tropical rainforests contain many large trees. A plant requires sunlight for photosynthesis. A leaf absorbs sunlight to perform photosynthesis. A plant is a kind of living thing. A required resource being low in availability has a negative impact on the something that requires that resource. A plant requires photosynthesis to grow / survive. If a living thing must do something to survive, then increasing that living thing's ability to do that something has a positive impact on that living thing's survival. Is it true that a plant can use sugar from photosynthesis to grow?",
   ['unknown']],
  ['ebn-0012',
   'A pan is put on an open flame. A flame are a part of a fire. Evaporation means a substance changes from a liquid into a gas by increasing heat energy. If a substance is exposed to a source of heat then that substance may become hot / warm. Becoming hot means increasing in heat energy. An ice cube is placed in the pan. If thermal conductor is exposed to a source of heat then that conductor may become hot / warm. A hot object is a source of heat. Metal is a thermal conductor. Fire gives off heat. A source of something gives off that something. Melting means a substance changes from a solid into a liquid by increasing heat energy. If something is placed over a heat source then that something is exposed to that heat source. A pan is made of metal for cooking. If an object is exposed to a source of heat then that object may become hot. An ice cube is a kind of object. A pan is a kind of object. Is it true that heat, light, and sound are all different forms of energy?',
   ['unknown']],
  ['ebn-0013',
   'A pan is put on an open flame. A flame are a part of a fire. Evaporation means a substance changes from a liquid into a gas by increasing heat energy. If a substance is exposed to a source of heat then that substance may become hot / warm. Becoming hot means increasing in heat energy. An ice cube is placed in the pan. If thermal conductor is exposed to a source of heat then that conductor may become hot / warm. A hot object is a source of heat. Metal is a thermal conductor. Fire gives off heat. A source of something gives off that something. Melting means a substance changes from a solid into a liquid by increasing heat energy. If something is placed over a heat source then that something is exposed to that heat source. A pan is made of metal for cooking. If an object is exposed to a source of heat then that object may become hot. An ice cube is a kind of object. A pan is a kind of object. Is it true that air masses formed over the ocean near the equator are moist / warm?',
   ['unknown']],
  ['ebn-0014',
   'Classifying is when one sorts something by type. Class is a property of a rock and includes values of sedimentary / metamorphic / igneous. Class is a measure of how a rock is formed. A class of something means a type of something. Is it true that a rock can be classified as igneous if it was formed from magma?',
   ['unknown']],
  ['ebn-0015',
   'Yellow is a kind of color. Flower is a part of a plant. The colors of parts of an organism are inherited characteristics. A plant is a kind of organism. Inheriting is when an inherited characteristic is passed down from parent to offspring by genetics / dna. The plant offspring has yellow flowers. Is it true that bees help flowers by helping plant reproduction?',
   ['unknown']],
  ['ebn-0016',
   'Yellow is a kind of color. Flower is a part of a plant. The colors of parts of an organism are inherited characteristics. A plant is a kind of organism. Inheriting is when an inherited characteristic is passed down from parent to offspring by genetics / dna. The plant offspring has yellow flowers. Is it true that hunting is a learned characteristic and not an inherited characteristic?',
   ['unknown']],
  ['ebn-0017',
   'If something is soluble in something , then that something can be dissolved in something forming a solution. Sugar is soluble in water. A sugar cube is made of sugar. Is it true that the water from the melted ice cube will then evaporate?',
   ['unknown']],
  ['ebn-0018',
   'Rabbits eat plants. A plant is a kind of organism. Consumers eat other organisms. Is it true that producers and consumers are organisms that can be classified by how they obtain food?',
   ['unknown']],
  ['ebn-0019',
   'Water vapor is formed by water evaporating. Fog is formed by water vapor condensing in the air. Oceans are the source of most of water vapor in the atmosphere. Is it true that air masses formed over the ocean near the equator are moist / warm?',
   ['unknown']],
  ['ebn-0020',
   'Muscle cells are a part of muscles. Moving changes stored energy into kinetic energy and heat energy. A bone is a part of a body. Muscle cells can store and release large amounts of energy. If a process changes something into something else, then that something is required for that process. Muscles push / pull bones to move the bones. Is it true that heat, light, and sound are all different forms of energy?',
   ['unknown']],
  ['ebn-0021',
   'Muscle cells are a part of muscles. Moving changes stored energy into kinetic energy and heat energy. A bone is a part of a body. Muscle cells can store and release large amounts of energy. If a process changes something into something else, then that something is required for that process. Muscles push / pull bones to move the bones. Is it true that the energy absorbed by solar cells will be used on powering household appliances?',
   ['unknown']],
  ['ebn-0022',
   'Cool ocean waters are bodies of cool water. Cool water has low heat energy. Heat and moisture over ocean cause the formation of a hurricane. Forming a hurricane requires certain water temperature. Is it true that heat, light, and sound are all different forms of energy?',
   ['unknown']],
  ['ebn-0023',
   'Cool ocean waters are bodies of cool water. Cool water has low heat energy. Heat and moisture over ocean cause the formation of a hurricane. Forming a hurricane requires certain water temperature. Is it true that fog can be formed by ocean water evaporating and then condensing in the air?',
   ['unknown']],
  ['ebn-0024',
   'Cool ocean waters are bodies of cool water. Cool water has low heat energy. Heat and moisture over ocean cause the formation of a hurricane. Forming a hurricane requires certain water temperature. Is it true that air masses formed over the ocean near the equator are moist / warm?',
   ['unknown']],
  ['ebn-0025',
   'Chocolate is a kind of solid usually. Matter in the solid phase has definite shape. Melting means matter / a substance changes from a solid into a liquid by increasing heat energy. Matter in the liquid phase has variable shape. Chocolate melts in the sunlight. Chocolate is a kind of substance. Is it true that heat, light, and sound are all different forms of energy?',
   ['unknown']],
  ['ebn-0026',
   'Soil is a kind of resource. Some minerals are nutrients. A plant / living thing requires nutrients to grow. Soil provides nutrients for plants. Is it true that plants on tropical rainforest floors grow large leaves due to the low availability of sunlight?',
   ['unknown']],
  ['ebn-0027',
   'Soil is a kind of resource. Some minerals are nutrients. A plant / living thing requires nutrients to grow. Soil provides nutrients for plants. Is it true that a plant can use sugar from photosynthesis to grow?',
   ['unknown']],
  ['ebn-0028',
   'Striped is a kind of color pattern. The color of / coloration of fur is an inherited characteristic. A tiger is a kind of animal. Inheriting is when an inherited characteristic is copied / is passed from parent to offspring by genetics / dna. Is it true that hunting is a learned characteristic and not an inherited characteristic?',
   ['unknown']],
  ['ebn-0029',
   'Green plants are a kind of producer. Photosynthesis makes food for the plant by converting carbon dioxide, water, and sunlight into carbohydrates. A producer is a source of sugar in an ecosystem. Sugar is a kind of food. A source of something produces that something. Is it true that plants on tropical rainforest floors grow large leaves due to the low availability of sunlight?',
   ['unknown']],
  ['ebn-0030',
   'Green plants are a kind of producer. Photosynthesis makes food for the plant by converting carbon dioxide, water, and sunlight into carbohydrates. A producer is a source of sugar in an ecosystem. Sugar is a kind of food. A source of something produces that something. Is it true that sugar cubes will dissolve in water when they are combined?',
   ['unknown']],
  ['ebn-0031',
   'A plant requires photosynthesis to grow. Food is made of carbohydrates. Photosynthesis is a source of food for the plant by converting carbon dioxide, water, and sunlight into carbohydrates. Sugar is a kind of simple carbohydrate. If a process is a source of something then that process is used for making that something. Photosynthesis is a kind of chemical process. Is it true that plants on tropical rainforest floors grow large leaves due to the low availability of sunlight?',
   ['unknown']],
  ['ebn-0032',
   'A plant requires photosynthesis to grow. Food is made of carbohydrates. Photosynthesis is a source of food for the plant by converting carbon dioxide, water, and sunlight into carbohydrates. Sugar is a kind of simple carbohydrate. If a process is a source of something then that process is used for making that something. Photosynthesis is a kind of chemical process. Is it true that sugar cubes will dissolve in water when they are combined?',
   ['unknown']],
  ['ebn-0033',
   'A plant requires photosynthesis to grow. Food is made of carbohydrates. Photosynthesis is a source of food for the plant by converting carbon dioxide, water, and sunlight into carbohydrates. Sugar is a kind of simple carbohydrate. If a process is a source of something then that process is used for making that something. Photosynthesis is a kind of chemical process. Is it true that making discoveries about the sky requires using a telescope to observe the sky?',
   ['unknown']],
  ['ebn-0034',
   'If something receives sunlight, then it will increase in temperature. If something increases in temperature, then that something will be warm. The air around the equator receives direct sunlight. The air mass formed close to the ocean is humid in moisture. Is it true that fog can be formed by ocean water evaporating and then condensing in the air?',
   ['unknown']],
  ['ebn-0035',
   'Carnivores only eat animals. Eagles eat snakes / lizards / rats / rabbits / mice. Eagles do not eat plants. Snakes / lizards / rats / rabbits / mice are kinds of animals. Is it true that plants on tropical rainforest floors grow large leaves due to the low availability of sunlight?',
   ['unknown']],
  ['ebn-0036',
   'Light is a kind of energy. Sound is a kind of energy. Heat is a kind of energy. Is it true that light can be seen as both particles and waves?',
   ['unknown']],
  ['ebn-0037',
   'Samples of a single type of mineral usually have the same properties. Different materials usually have different properties. The properties of something can be used to identify / used to describe that something. A mineral is a kind of material. Is it true that conductivity can be used to identify metals?',
   ['unknown']],
  ['ebn-0038',
   'Electric devices require electrical energy to function. Solar cells convert solar energy into electrical energy. Household appliances are a kind of electric device. Is it true that releasing energy is used by muscles to move parts of the body?',
   ['unknown']],
  ['ebn-0039',
   'If something is a part of something then that something can be found in that something. Chloroplast is a part of a plant cell. Only plant cells have chloroplast. Is it true that bees help flowers by helping plant reproduction?',
   ['unknown']],
  ['ebn-0040',
   'A consumer is a kind of organism. Producing food is a kind of method for obtaining food. Eating other organisms is a kind of method for obtaining food. A producer is a kind of organism. Classifying is when one sorts something by kind / type. Consumers eat other organisms. A producer produces its own food. Is it true that an earthworm is a kind of invertebrate organism?',
   ['unknown']],
  ['ebn-0041',
   'Carnivores only eat animals. Eagles eat snakes / lizards / rats / rabbits / mice. Eagles do not eat plants. Snakes / lizards / rats / rabbits / mice are kinds of animals. Is it true that an eagle is not a kind of carnivore?',
   ['false']],
  ['ebn-0042',
   'Light is a kind of energy. Sound is a kind of energy. Heat is a kind of energy. Is it true that sound is not a form of energy?',
   ['false']],
  ['ebn-0043',
   'A pebble is a kind of small rock. Rocks interacting with moving water over long periods of time causes weathering. Waves are made of moving water. Sometimes weathering smooths rocks. Is it true that waves interacting with pebbles cannot smooth pebbles?',
   ['false']],
  ['ebn-0044',
   'Samples of a single type of mineral usually have the same properties. Different materials usually have different properties. The properties of something can be used to identify / used to describe that something. A mineral is a kind of material. Is it true that the properties of a mineral cannot be used to identify those minerals?',
   ['false']],
  ['ebn-0045',
   'A class of something means a type of something. Classifying is when one sorts something by kind / type. Class is a measure of how a rock is formed. Igneous rocks are formed by magma cooling / crystallizing. Is it true that a rock cannot be classified as igneous if it was formed from magma?',
   ['false']],
  ['ebn-0046',
   'An earthworm does not have an internal skeleton. An invertebrate organism does not have an internal skeleton. Is it true that an earthworm is not a kind of invertebrate organism?',
   ['false']],
  ['ebn-0047',
   'Height is an inherited characteristic. Inheriting is when an inherited characteristic is copied / is passed from parent to offspring by genetics / dna. Is it true that offspring cannot inherit height from their parents?',
   ['false']],
  ['ebn-0048',
   'Metals usually have higher / greater conductivity than nonmetals. Metal is an electrical  conductor. Is it true that conductivity cannot be used to identify metals?',
   ['false']],
  ['ebn-0049',
   'If something is a part of something then that something can be found in that something. Chloroplast is a part of a plant cell. Only plant cells have chloroplast. Is it true that chloroplast can be found in a cell that is not a plant cell?',
   ['false']],
  ['ebn-0050',
   'Genes is a vehicle for passing inherited characteristics from parent to offspring. Inherited characteristics are a kind of hereditary information. Is it true that hereditary information is not passed from parents to offspring through genes?',
   ['false']],
  ['ebn-0051',
   'If something is soluble in something , then that something can be dissolved in something forming a solution. Sugar is soluble in water. A sugar cube is made of sugar. Is it true that sugar cubes will not dissolve in water when they are combined?',
   ['false']],
  ['ebn-0052',
   'Rabbits eat plants. A plant is a kind of organism. Consumers eat other organisms. Is it true that a rabbit is not a kind of consumer?',
   ['false']],
  ['ebn-0053',
   'Young amphibians undergo metamorphosis. A frog is a kind of amphibian. Is it true that frogs do not undergo metamorphosis?',
   ['false']],
  ['ebn-0054',
   'Water vapor is formed by water evaporating. Fog is formed by water vapor condensing in the air. Oceans are the source of most of water vapor in the atmosphere. Is it true that fog cannot be formed by ocean water evaporating and then condensing in the air?',
   ['false']],
  ['ebn-0055',
   'Acid can cause rocks to weather by chemical reaction. Lichens can produce acid to break down rocks. Chemical weathering means chemical reaction causes the weathering of rocks. Is it true that lichens producing acid to break down rocks is not an example of chemical weathering?',
   ['false']],
  ['ebn-0056',
   'Chocolate is a kind of solid usually. Matter in the solid phase has definite shape. Melting means matter / a substance changes from a solid into a liquid by increasing heat energy. Matter in the liquid phase has variable shape. Chocolate melts in the sunlight. Chocolate is a kind of substance. Is it true that the shape of the chocolate does not change when the chocolate melts?',
   ['false']],
  ['ebn-0057',
   'Different solids are combined physically. An mixture is formed by two or more substances combined together physically. If solids are combined physically , then the physical properties of the solids will stay the same. Is it true that different solids that are combined will not become a mixture?',
   ['false']],
  ['ebn-0058',
   'Soil is a kind of resource. Some minerals are nutrients. A plant / living thing requires nutrients to grow. Soil provides nutrients for plants. Is it true that soil is not a kind of resource that provides minerals that plants need to grow?',
   ['false']],
  ['ebn-0059',
   'Striped is a kind of color pattern. The color of / coloration of fur is an inherited characteristic. A tiger is a kind of animal. Inheriting is when an inherited characteristic is copied / is passed from parent to offspring by genetics / dna. Is it true that a tiger will not inherit striped color pattern of its fur from its parents?',
   ['false']],
  ['ebn-0060',
   'Rainfall is the amount of rain an area receives. A grassland receives moderate rainfall. A desert environment receives low rainfall. Amount is a kind of property with ordered values of low / moderate / high. Is it true that a grassland does not receive more rain than a desert?',
   ['false']],
]
