"""ARC wrong-option negatives, built by tools/graph_arc_negatives.py.

Each case is an EntailmentBank passage paired with a wrong option
a person proposed for that same ARC question, written as a
declarative hypothesis.  56 cases: 3 false, 53 unknown.
Do not edit by hand; rebuild from the tool.
"""

tests = [
  ['arcn-0001',
   'Carnivores only eat animals. Eagles eat snakes / lizards / rats / rabbits / mice. Eagles do not eat plants. Snakes / lizards / rats / rabbits / mice are kinds of animals. Is it true that a field mouse is a kind of carnivore?',
   ['unknown']],
  ['arcn-0002',
   'Carnivores only eat animals. Eagles eat snakes / lizards / rats / rabbits / mice. Eagles do not eat plants. Snakes / lizards / rats / rabbits / mice are kinds of animals. Is it true that a rabbit is a kind of carnivore?',
   ['unknown']],
  ['arcn-0003',
   'Carnivores only eat animals. Eagles eat snakes / lizards / rats / rabbits / mice. Eagles do not eat plants. Snakes / lizards / rats / rabbits / mice are kinds of animals. Is it true that algae is a kind of carnivore?',
   ['unknown']],
  ['arcn-0004',
   'Light is a kind of energy. Sound is a kind of energy. Heat is a kind of energy. Is it true that heat, light, and sound are all different forms of fuel?',
   ['unknown']],
  ['arcn-0005',
   'Light is a kind of energy. Sound is a kind of energy. Heat is a kind of energy. Is it true that heat, light, and sound are all different forms of matter?',
   ['unknown']],
  ['arcn-0006',
   'Light is a kind of energy. Sound is a kind of energy. Heat is a kind of energy. Is it true that heat, light, and sound are all different forms of electricity?',
   ['unknown']],
  ['arcn-0007',
   'Moisture is water in liquid form. Water is a kind of substance. Freezing means a substance changes from a liquid into a solid by decreasing heat energy. There is moisture on the surface of the airplane. An airplane is climbing in the sky. Climbing increases altitude. As altitude increases , the temperature of the air will decrease in the troposphere. Water is in the solid state , called ice. Is it true that ice crystals form on the windshield because blizzards occur more often at higher altitudes?',
   ['unknown']],
  ['arcn-0008',
   'Moisture is water in liquid form. Water is a kind of substance. Freezing means a substance changes from a liquid into a solid by decreasing heat energy. There is moisture on the surface of the airplane. An airplane is climbing in the sky. Climbing increases altitude. As altitude increases , the temperature of the air will decrease in the troposphere. Water is in the solid state , called ice. Is it true that ice crystals form on the windshield because friction with the atmosphere causes ice to develop?',
   ['unknown']],
  ['arcn-0009',
   'A pebble is a kind of small rock. Rocks interacting with moving water over long periods of time causes weathering. Waves are made of moving water. Sometimes weathering smooths rocks. Is it true that rain falling made the pebble smooth?',
   ['unknown']],
  ['arcn-0010',
   'A pebble is a kind of small rock. Rocks interacting with moving water over long periods of time causes weathering. Waves are made of moving water. Sometimes weathering smooths rocks. Is it true that wind blowing made the pebble smooth?',
   ['unknown']],
  ['arcn-0011',
   'A pebble is a kind of small rock. Rocks interacting with moving water over long periods of time causes weathering. Waves are made of moving water. Sometimes weathering smooths rocks. Is it true that snow melting made the pebble smooth?',
   ['unknown']],
  ['arcn-0012',
   'Samples of a single type of mineral usually have the same properties. Different materials usually have different properties. The properties of something can be used to identify / used to describe that something. A mineral is a kind of material. Is it true that minerals can be identified using hardness, streak, and cleavage because minerals are inorganic?',
   ['unknown']],
  ['arcn-0013',
   'Samples of a single type of mineral usually have the same properties. Different materials usually have different properties. The properties of something can be used to identify / used to describe that something. A mineral is a kind of material. Is it true that minerals can be identified using hardness, streak, and cleavage because crystal structure is too hard to determine?',
   ['unknown']],
  ['arcn-0014',
   'A class of something means a type of something. Classifying is when one sorts something by kind / type. Class is a measure of how a rock is formed. Igneous rocks are formed by magma cooling / crystallizing. Is it true that in order for rocks to be classified as igneous, the rocks must solidify at the surface of Earth?',
   ['unknown']],
  ['arcn-0015',
   'A class of something means a type of something. Classifying is when one sorts something by kind / type. Class is a measure of how a rock is formed. Igneous rocks are formed by magma cooling / crystallizing. Is it true that in order for rocks to be classified as igneous, the rocks must be eroded and deposited in layers?',
   ['unknown']],
  ['arcn-0016',
   'A class of something means a type of something. Classifying is when one sorts something by kind / type. Class is a measure of how a rock is formed. Igneous rocks are formed by magma cooling / crystallizing. Is it true that in order for rocks to be classified as igneous, the rocks must change form when pressure is applied?',
   ['unknown']],
  ['arcn-0017',
   'An earthworm does not have an internal skeleton. An invertebrate organism does not have an internal skeleton. Is it true that an earthworm has radial symmetry?',
   ['unknown']],
  ['arcn-0018',
   'An earthworm does not have an internal skeleton. An invertebrate organism does not have an internal skeleton. Is it true that an earthworm is made of one segment?',
   ['unknown']],
  ['arcn-0019',
   'An earthworm does not have an internal skeleton. An invertebrate organism does not have an internal skeleton. Is it true that an earthworm has an open circulatory system?',
   ['unknown']],
  ['arcn-0020',
   'The skeletal system is used to give structure for the body of animals. Muscular movement helps animals move. The muscular system contains muscles. Microtubules in eukaryotic organisms help cells move. If two things perform the same function then those two things are similar. Microfilaments in eukaryotic organisms give cells structure. Is it true that microtubules and microfilaments in eukaryotic organisms are similar to the endocrine and skeletal systems in animals?',
   ['unknown']],
  ['arcn-0021',
   'The skeletal system is used to give structure for the body of animals. Muscular movement helps animals move. The muscular system contains muscles. Microtubules in eukaryotic organisms help cells move. If two things perform the same function then those two things are similar. Microfilaments in eukaryotic organisms give cells structure. Is it true that microtubules and microfilaments in eukaryotic organisms are similar to the circulatory and respiratory systems in animals?',
   ['unknown']],
  ['arcn-0022',
   'Height is an inherited characteristic. Inheriting is when an inherited characteristic is copied / is passed from parent to offspring by genetics / dna. Is it true that offspring can inherit learning to ride a bike from their parents?',
   ['unknown']],
  ['arcn-0023',
   'Height is an inherited characteristic. Inheriting is when an inherited characteristic is copied / is passed from parent to offspring by genetics / dna. Is it true that offspring can inherit holding a spoon from their parents?',
   ['unknown']],
  ['arcn-0024',
   'Height is an inherited characteristic. Inheriting is when an inherited characteristic is copied / is passed from parent to offspring by genetics / dna. Is it true that offspring can inherit reading a book from their parents?',
   ['unknown']],
  ['arcn-0025',
   "An adaptation has a positive impact on a living thing 's survival. Drier means lower in amount of water. Living things require water for survival. If something increases something else then that something has a positive impact on that something else. Storing water increases the water available to organisms in a dry environment. A dry environment is low in availability of water. Is it true that amount of body fat is a kind of adaptation to a dry environment?",
   ['unknown']],
  ['arcn-0026',
   "An adaptation has a positive impact on a living thing 's survival. Drier means lower in amount of water. Living things require water for survival. If something increases something else then that something has a positive impact on that something else. Storing water increases the water available to organisms in a dry environment. A dry environment is low in availability of water. Is it true that amount of body hair is a kind of adaptation to a dry environment?",
   ['unknown']],
  ['arcn-0027',
   "An adaptation has a positive impact on a living thing 's survival. Drier means lower in amount of water. Living things require water for survival. If something increases something else then that something has a positive impact on that something else. Storing water increases the water available to organisms in a dry environment. A dry environment is low in availability of water. Is it true that ability to climb trees is a kind of adaptation to a dry environment?",
   ['unknown']],
  ['arcn-0028',
   'Metals usually have higher / greater conductivity than nonmetals. Metal is an electrical  conductor. Is it true that color can be used to identify metals?',
   ['unknown']],
  ['arcn-0029',
   'Metals usually have higher / greater conductivity than nonmetals. Metal is an electrical  conductor. Is it true that weight can be used to identify metals?',
   ['unknown']],
  ['arcn-0030',
   'Metals usually have higher / greater conductivity than nonmetals. Metal is an electrical  conductor. Is it true that texture can be used to identify metals?',
   ['unknown']],
  ['arcn-0031',
   'Electric devices require electrical energy to function. Solar cells convert solar energy into electrical energy. Household appliances are a kind of electric device. Is it true that the energy absorbed by solar cells will be used on heating household appliances?',
   ['unknown']],
  ['arcn-0032',
   'Electric devices require electrical energy to function. Solar cells convert solar energy into electrical energy. Household appliances are a kind of electric device. Is it true that the energy absorbed by solar cells will be used on lighting household appliances?',
   ['unknown']],
  ['arcn-0033',
   'Electric devices require electrical energy to function. Solar cells convert solar energy into electrical energy. Household appliances are a kind of electric device. Is it true that the energy absorbed by solar cells will be used on radiating household appliances?',
   ['unknown']],
  ['arcn-0034',
   "As the size of a leaf increases , the amount of sunlight absorbed by that leaf will increase. An adaptation / an ability has a positive impact on an animal 's / living thing 's survival / health / ability to reproduce. Large canopies / trees block sunlight from reaching the ground. Forest canopies blocking sunlight decreases the availability of sunlight on the forest floor. Larger means greater / higher / more / increase in size. A leaf is a part of a green plant. Tropical rainforests contain many large trees. A plant requires sunlight for photosynthesis. A leaf absorbs sunlight to perform photosynthesis. A plant is a kind of living thing. A required resource being low in availability has a negative impact on the something that requires that resource. A plant requires photosynthesis to grow / survive. If a living thing must do something to survive, then increasing that living thing's ability to do that something has a positive impact on that living thing's survival. Is it true that plants on tropical rainforest floors grow large leaves due to the low availability of oxygen?",
   ['unknown']],
  ['arcn-0035',
   "As the size of a leaf increases , the amount of sunlight absorbed by that leaf will increase. An adaptation / an ability has a positive impact on an animal 's / living thing 's survival / health / ability to reproduce. Large canopies / trees block sunlight from reaching the ground. Forest canopies blocking sunlight decreases the availability of sunlight on the forest floor. Larger means greater / higher / more / increase in size. A leaf is a part of a green plant. Tropical rainforests contain many large trees. A plant requires sunlight for photosynthesis. A leaf absorbs sunlight to perform photosynthesis. A plant is a kind of living thing. A required resource being low in availability has a negative impact on the something that requires that resource. A plant requires photosynthesis to grow / survive. If a living thing must do something to survive, then increasing that living thing's ability to do that something has a positive impact on that living thing's survival. Is it true that plants on tropical rainforest floors grow large leaves due to the low availability of water?",
   ['unknown']],
  ['arcn-0036',
   "As the size of a leaf increases , the amount of sunlight absorbed by that leaf will increase. An adaptation / an ability has a positive impact on an animal 's / living thing 's survival / health / ability to reproduce. Large canopies / trees block sunlight from reaching the ground. Forest canopies blocking sunlight decreases the availability of sunlight on the forest floor. Larger means greater / higher / more / increase in size. A leaf is a part of a green plant. Tropical rainforests contain many large trees. A plant requires sunlight for photosynthesis. A leaf absorbs sunlight to perform photosynthesis. A plant is a kind of living thing. A required resource being low in availability has a negative impact on the something that requires that resource. A plant requires photosynthesis to grow / survive. If a living thing must do something to survive, then increasing that living thing's ability to do that something has a positive impact on that living thing's survival. Is it true that plants on tropical rainforest floors grow large leaves due to the low availability of food?",
   ['unknown']],
  ['arcn-0037',
   'If something is a part of something then that something can be found in that something. Chloroplast is a part of a plant cell. Only plant cells have chloroplast. Is it true that a nucleus can only be found in a plant cell?',
   ['unknown']],
  ['arcn-0038',
   'If something is a part of something then that something can be found in that something. Chloroplast is a part of a plant cell. Only plant cells have chloroplast. Is it true that a vacuole can only be found in a plant cell?',
   ['unknown']],
  ['arcn-0039',
   'If something is a part of something then that something can be found in that something. Chloroplast is a part of a plant cell. Only plant cells have chloroplast. Is it true that a mitochondrion can only be found in a plant cell?',
   ['unknown']],
  ['arcn-0040',
   'A pan is put on an open flame. A flame are a part of a fire. Evaporation means a substance changes from a liquid into a gas by increasing heat energy. If a substance is exposed to a source of heat then that substance may become hot / warm. Becoming hot means increasing in heat energy. An ice cube is placed in the pan. If thermal conductor is exposed to a source of heat then that conductor may become hot / warm. A hot object is a source of heat. Metal is a thermal conductor. Fire gives off heat. A source of something gives off that something. Melting means a substance changes from a solid into a liquid by increasing heat energy. If something is placed over a heat source then that something is exposed to that heat source. A pan is made of metal for cooking. If an object is exposed to a source of heat then that object may become hot. An ice cube is a kind of object. A pan is a kind of object. Is it true that the ice changes to a gas and back to a solid?',
   ['unknown']],
  ['arcn-0041',
   'A pan is put on an open flame. A flame are a part of a fire. Evaporation means a substance changes from a liquid into a gas by increasing heat energy. If a substance is exposed to a source of heat then that substance may become hot / warm. Becoming hot means increasing in heat energy. An ice cube is placed in the pan. If thermal conductor is exposed to a source of heat then that conductor may become hot / warm. A hot object is a source of heat. Metal is a thermal conductor. Fire gives off heat. A source of something gives off that something. Melting means a substance changes from a solid into a liquid by increasing heat energy. If something is placed over a heat source then that something is exposed to that heat source. A pan is made of metal for cooking. If an object is exposed to a source of heat then that object may become hot. An ice cube is a kind of object. A pan is a kind of object. Is it true that the ice changes to a gas then to a liquid?',
   ['unknown']],
  ['arcn-0042',
   'Genes is a vehicle for passing inherited characteristics from parent to offspring. Inherited characteristics are a kind of hereditary information. Is it true that hereditary information is passed from parents to offspring through cell division?',
   ['unknown']],
  ['arcn-0043',
   'Genes is a vehicle for passing inherited characteristics from parent to offspring. Inherited characteristics are a kind of hereditary information. Is it true that hereditary information is passed from parents to offspring through germination?',
   ['unknown']],
  ['arcn-0044',
   'Genes is a vehicle for passing inherited characteristics from parent to offspring. Inherited characteristics are a kind of hereditary information. Is it true that hereditary information is passed from parents to offspring through metamorphosis?',
   ['unknown']],
  ['arcn-0045',
   'Classifying is when one sorts something by type. Class is a property of a rock and includes values of sedimentary / metamorphic / igneous. Class is a measure of how a rock is formed. A class of something means a type of something. Is it true that rocks are classified as igneous, sedimentary, or metamorphic based on their color?',
   ['unknown']],
  ['arcn-0046',
   'Classifying is when one sorts something by type. Class is a property of a rock and includes values of sedimentary / metamorphic / igneous. Class is a measure of how a rock is formed. A class of something means a type of something. Is it true that rocks are classified as igneous, sedimentary, or metamorphic based on their shape?',
   ['unknown']],
  ['arcn-0047',
   'Classifying is when one sorts something by type. Class is a property of a rock and includes values of sedimentary / metamorphic / igneous. Class is a measure of how a rock is formed. A class of something means a type of something. Is it true that rocks are classified as igneous, sedimentary, or metamorphic based on the minerals they contain?',
   ['unknown']],
  ['arcn-0048',
   'A consumer is a kind of organism. Producing food is a kind of method for obtaining food. Eating other organisms is a kind of method for obtaining food. A producer is a kind of organism. Classifying is when one sorts something by kind / type. Consumers eat other organisms. A producer produces its own food. Is it true that producers and consumers are organisms that can be classified by their speed of movement?',
   ['unknown']],
  ['arcn-0049',
   'A consumer is a kind of organism. Producing food is a kind of method for obtaining food. Eating other organisms is a kind of method for obtaining food. A producer is a kind of organism. Classifying is when one sorts something by kind / type. Consumers eat other organisms. A producer produces its own food. Is it true that producers and consumers are organisms that can be classified by the size of their communities?',
   ['unknown']],
  ['arcn-0050',
   'A consumer is a kind of organism. Producing food is a kind of method for obtaining food. Eating other organisms is a kind of method for obtaining food. A producer is a kind of organism. Classifying is when one sorts something by kind / type. Consumers eat other organisms. A producer produces its own food. Is it true that producers and consumers are organisms that can be classified by how they reproduce?',
   ['unknown']],
  ['arcn-0051',
   'Yellow is a kind of color. Flower is a part of a plant. The colors of parts of an organism are inherited characteristics. A plant is a kind of organism. Inheriting is when an inherited characteristic is passed down from parent to offspring by genetics / dna. The plant offspring has yellow flowers. Is it true that the flowers are yellow because the sunshine colored them yellow?',
   ['false']],
  ['arcn-0052',
   'Yellow is a kind of color. Flower is a part of a plant. The colors of parts of an organism are inherited characteristics. A plant is a kind of organism. Inheriting is when an inherited characteristic is passed down from parent to offspring by genetics / dna. The plant offspring has yellow flowers. Is it true that the flowers are yellow because it was very warm when they flowered?',
   ['false']],
  ['arcn-0053',
   'Yellow is a kind of color. Flower is a part of a plant. The colors of parts of an organism are inherited characteristics. A plant is a kind of organism. Inheriting is when an inherited characteristic is passed down from parent to offspring by genetics / dna. The plant offspring has yellow flowers. Is it true that the flowers are yellow because it rained every day?',
   ['false']],
  ['arcn-0054',
   'If something is soluble in something , then that something can be dissolved in something forming a solution. Sugar is soluble in water. A sugar cube is made of sugar. Is it true that sand grains will dissolve in water when they are combined?',
   ['unknown']],
  ['arcn-0055',
   'If something is soluble in something , then that something can be dissolved in something forming a solution. Sugar is soluble in water. A sugar cube is made of sugar. Is it true that plastic straws will dissolve in water when they are combined?',
   ['unknown']],
  ['arcn-0056',
   'If something is soluble in something , then that something can be dissolved in something forming a solution. Sugar is soluble in water. A sugar cube is made of sugar. Is it true that wooden spoons will dissolve in water when they are combined?',
   ['unknown']],
]
